[package]
name = "rusty-nail"
version = "0.1.0"
authors = ["Christopher J. Woodall <chris.j.woodall@gmail.com>"]

[dependencies]
sysfs_gpio = "0.4"
sysfs-pwm = {git="https://github.com/posborne/rust-sysfs-pwm.git", branch="master"}
