[package]
name = "rusty-nail"
version = "0.1.0"
authors = ["Christopher J. Woodall <chris.j.woodall@gmail.com>"]

[dependencies]
sysfs_gpio = "0.4"
sysfs-pwm = "0.1.0"
error-chain = "0.7.2"
diesel = "0.9.0"
diesel_codegen = { version = "0.9.0", features = ["sqlite"] }
dotenv = "0.8.0"
