site_name: Rusty Nail Notes and Documentation
theme: material
pages:
  - Index: index.md
  - Documentation: doc/rusty_nail/index.md
  - Notes:
    - Setting Up A Beaglebone With Rust: notes/2016-12-11-setting-up-beaglebone-with-rust.md
    - Blinking An LED With Rust: notes/2016-12-13-blinking-a-led-with-rust.md
    - PWM With Rust: notes/2016-12-15-pwming-with-rust.md
    - Parts For A Seltzer Air Pump: notes/2016-12-17-hardware-pumping-seltzer.md
    - Test Of Air Pump: notes/2016-12-22-air-pump-test.md
